version: "3.9"
   
x-shared-volumes: &shared-volumes
  volumes:
    - './aplicativo:/code'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env # * save private configs
  web:
    build:
      context: .
    env_file: .env # * save private configs
    command: python aplicativo/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    <<: *shared-volumes